name: Run Cypress Tests

on: push

jobs:
  run_cypress:
    name: Run Cypress
    runs-on: ubuntu-16.04
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress un